In [1]:
#importing libraries 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D


In [2]:
data = pd.read_csv('student.csv')
print(data.shape)
data.head()

(1000, 3)


Math  Reading  Writing
0    48       68       63
1    62       81       72
2    79       80       78
3    76       83       79
4    59       64       62

In [6]:
math = data['Math'].values
read = data['Reading'].values
write = data['Writing'].values


In [7]:
#plotting the figure as scatter plot
fig = plt.figure()
ax = Axes3D(fig)
ax.scatter(math, read, write, color = '#ef1234')
plt.legend
plt.show()



<Figure size 640x480 with 0 Axes>

In [8]:
m = len(math)
print(m)
x0 = np.ones(m)



1000


In [9]:
X = np.array([x0, math, read]).T
print(X)

[[ 1. 48. 68.]
 [ 1. 62. 81.]
 [ 1. 79. 80.]
 ...
 [ 1. 89. 87.]
 [ 1. 83. 82.]
 [ 1. 66. 66.]]


In [10]:
#initital co-efficients
B = np.array([0,0,0])
Y = np.array(write)
alpha = 0.0001
def cost_function(X,Y,B):
    m = len(Y)
    J = np.sum((X.dot(B)-Y)**2)/(2*m)
    return J

In [11]:
initial_cost = cost_function(X,Y,B)
print("initial Cost")
print(initial_cost)

initial Cost
2470.11


In [14]:
def gradient_descent(X,Y,B,alpha,iterations):
    cost_history = [0]* iterations
    m = len(Y)
    for iteration in range(iterations):
        #Hypothesis values
        h = X.dot(B)
        #difference between Hypothesis and actual Y
        loss = h-Y
        #Gradient calculation
        gradient = X.T.dot(loss)/m

        #changing values of B using gradient
        B = B-alpha*gradient
        cost = cost_function(X,Y,B)
        cost_history[iteration] = cost
    return B, cost_history

In [15]:
#100000 iteration
newB, cost_history = gradient_descent(X,Y,B,alpha,100000)

#new values of B
print("New co-efficients")
print(newB)

# Final cost of newB
print("Final cost")
print(newB)

New co-efficients
[-0.47889172  0.09137252  0.90144884]
Final cost
[-0.47889172  0.09137252  0.90144884]


In [32]:
print(cost_history[-1])

10.475123473539167


In [16]:
#model evaluation-RMSE
def rmse(Y, Y_pred):
    rmse = np.sqrt(sum((Y-Y_pred)**2)/len(Y))
    return rmse

In [17]:
#model evaluation R^2 score
def r2_score(Y, Y_pred):
    mean_y = np.mean(Y)
    ss_tot = sum((Y-mean_y)**2)
    ss_res = sum((Y-Y_pred)**2)
    r2 = 1-(ss_res/ss_tot)
    return r2

In [18]:
Y_pred = X.dot(newB)
print("R^2 score")
print(r2_score(Y, Y_pred))


R^2 score
0.9097223273061553
